class Car {
  Car({
    required this.name,
    required this.img,
    required this.details,
    required this.highlights,
    required this.price,
    required this.rating,
    required this.scale,
    this.tag,
  });

  String name;
  List<String> img;
  String details;
  double price;
  double rating;
  String scale;
  List<String>? Specification;
  List<String> highlights;
  List<Tags>? tag;
}

enum Tags { SuperCar, SUV, Bikes, Luxury, SportsCar }

List<String> highlights = [
  "Scale 1:18",
  "Realistic Design",
  "Collection Model",
  "Steerable Front Wheels",
  "Opening parts as shown in pictures",
  "Free Rolling Wheels",
  "Made with Metal,Plastic & Rubber Parts",
  "Window Box Included",
  "Official Licensed Product",
  "Excellent decoration for Home/Office",
  "Perfect Product For Gifting",
];

List<Car> cars = [
  Car(
      name: "FORD GT40 MKI - LE MANS - WINNER",
      img: [
        "assets/images/image_04.png",
        "assets/images/image_03.png",
        "assets/images/image_02.png",
        "assets/images/image_01.png",
      ],
      details:
          "Named as 'GT' or Grand Touring car, the Ford made GT 40 were produced in the UK and was based on the British made Lola MK6 model with inputs from John Wyer Automotive Engineering, Shelby and a gearbox supplier called Kar-Kraft Powered by Ford made 289 cubic inch V8 engines, about 100 cars rolled out as Ford GT 40 in Mark I, II and Mark III variants. The reason why it was called 40 was because of the height of her windshield which was 40 inches.On 15th June, 1969 at the Circuit de la Sarthe during Le Mans, a Ford GT40 MK I entered by J. W. Automotive Engineering Ltd. and driven by Belgian Jacky Ickx and British Jack Oliver came first after doing 372 laps maintaining an average speed of 208 km/hr",
      highlights: [],
      price: 220,
      rating: 4.5,
      tag: [Tags.SuperCar, Tags.SportsCar],
      scale: "1:18"),
  Car(
      name: "2021 Mercedes-Benz S Class AMG Line W223",
      img: [
        "assets/images/sclass/image15.png",
        "assets/images/sclass/image14.png",
        "assets/images/sclass/image13.png",
        "assets/images/sclass/image12.png",
        "assets/images/sclass/image11.png",
        "assets/images/sclass/image10.png",
        "assets/images/sclass/image9.png",
        "assets/images/sclass/image8.png",
        "assets/images/sclass/image7.png",
        "assets/images/sclass/image6.png",
        "assets/images/sclass/image5.png",
        "assets/images/sclass/image3.png",
      ],
      details: "details",
      highlights: [
        "Scale 1:18 miniature model ",
        "Realistic Design",
        "Collectible Model",
        "Opening parts as shown in pictures",
        "Steerable front wheels",
        "Free Rolling Wheels",
        "Made with Metal, Plastic & Rubber Parts",
        "Official Licensed Product",
        "Excellent decoration for Home/Office",
        "Perfect Product For Gifting",
        "Approx 28cm x 13cm x 10cm"
      ],
      price: 450,
      rating: 4.7,
      scale: "1:18"),
  Car(
      name: "2020 Mercedes-Benz AMG GT C190 Black Series",
      img: [
        "assets/images/gtr/gtr9.png",
        "assets/images/gtr/gtr8.png",
        "assets/images/gtr/gtr7.png",
        "assets/images/gtr/gtr6.png",
        "assets/images/gtr/gtr5.png",
        "assets/images/gtr/gtr4.png",
        "assets/images/gtr/gtr3.png",
        "assets/images/gtr/gtr2.png",
        "assets/images/gtr/gtr1.png",
      ],
      details: "details",
      highlights: [
        "Scale 1:18 miniature model ",
        "Realistic Design",
        "Collectible Model",
        "Opening parts as shown in pictures",
        "Free Rolling Wheels",
        "Made with Metal, Plastic & Rubber Parts",
        "Official Licensed Product",
        "Excellent decoration for Home/Office",
        "Perfect Product For Gifting",
        "Size 26cm x 13cm x 10cm",
      ],
      tag: [Tags.SuperCar, Tags.SportsCar],
      price: 600,
      rating: 4.2,
      scale: "1:18"),
  Car(
      name: "2019 Ferrari SF90 #5 F1 Sebastian Vettel",
      img: [
        "assets/images/f1/f14.png",
        "assets/images/f1/f13.png",
        "assets/images/f1/f12.png",
        "assets/images/f1/f11.png",
      ],
      details: "details",
      highlights: [
        "Scale 1:18",
        "Realistic Design",
        "Collection Model",
        "Steerable Front Wheels",
        "Opening parts as shown in pictures",
        "Free Rolling Wheels",
        "Made with Metal,Plastic & Rubber Parts",
        "Window Box Included",
        "Official Licensed Product",
        "Excellent decoration for Home/Office",
        "Perfect Product For Gifting",
      ],
      price: 150,
      tag: [Tags.SuperCar, Tags.SportsCar],
      rating: 4.0,
      scale: "1:18"),
  Car(
      name: "2021 Mercedes-Maybach GLS 600",
      img: [
        "assets/images/gls600/glc7.png",
        "assets/images/gls600/glc6.png",
        "assets/images/gls600/glc5.png",
        "assets/images/gls600/glc4.png",
        "assets/images/gls600/glc3.png",
        "assets/images/gls600/glc2.png",
        "assets/images/gls600/glc1.png",
      ],
      tag: [Tags.SportsCar, Tags.Luxury, Tags.SUV],
      details: "details",
      highlights: highlights,
      price: 145,
      rating: 3.9,
      scale: "1:18"),
  Car(
      name: "Mercedes Maybach Vision 6 Coupe ",
      img: [
        "assets/images/vision/vision5.png",
        "assets/images/vision/vision4.png",
        "assets/images/vision/vision3.png",
        "assets/images/vision/vision2.png",
        "assets/images/vision/vision1.png",
      ],
      details: "details",
      highlights: highlights,
      price: 200,
      rating: 4.3,
      scale: "1:18"),
  Car(
      name: "Koenigsegg One Black Carbon",
      img: [
        "assets/images/one/agera4.png",
        "assets/images/one/agera3.png",
        "assets/images/one/agera2.png",
        "assets/images/one/agera1.png",
      ],
      details: " details",
      highlights: highlights,
      price: 120,
      tag: [Tags.SuperCar, Tags.SportsCar],
      rating: 3.5,
      scale: "1:64"),
  Car(
      name: "2018 Land Rover Range Rover Velar First Edition white",
      tag: [Tags.SportsCar, Tags.Luxury, Tags.SUV],
      img: [
        "assets/images/velar/velar9.png",
        "assets/images/velar/velar8.png",
        "assets/images/velar/velar7.png",
        "assets/images/velar/velar6.png",
        "assets/images/velar/velar5.png",
        "assets/images/velar/velar4.png",
        "assets/images/velar/velar3.png",
        "assets/images/velar/velar2.png",
        "assets/images/velar/velar1.png",
      ],
      details: "details",
      highlights: highlights,
      price: 160,
      rating: 4.9,
      scale: "1:18"),
  Car(
      name: "Kawasaki Ninja H2 R",
      img: [
        "assets/images/h2r/h2r3.png",
        "assets/images/h2r/h2r2.png",
        "assets/images/h2r/h2r1.png",
      ],
      details: "details",
      tag: [Tags.Bikes, Tags.SportsCar],
      highlights: highlights,
      price: 85,
      rating: 3.6,
      scale: "1:12"),
  Car(
      name: "Bugatti Divo grey",
      img: [
        "assets/images/bugatti/divo6.png",
        "assets/images/bugatti/divo5.png",
        "assets/images/bugatti/divo4.png",
        "assets/images/bugatti/divo3.png",
        "assets/images/bugatti/divo2.png",
        "assets/images/bugatti/divo1.png",
      ],
      details: "details",
      highlights: highlights,
      price: 300,
      tag: [Tags.SuperCar, Tags.SportsCar],
      rating: 4.9,
      scale: "1:18"),
  Car(
      name: "2019 McLaren GT",
      img: [
        "assets/images/mclaren/mclaren5.png",
        "assets/images/mclaren/mclaren4.png",
        "assets/images/mclaren/mclaren3.png",
        "assets/images/mclaren/mclaren2.png",
        "assets/images/mclaren/mclaren1.png",
      ],
      details: "details",
      highlights: highlights,
      price: 250,
      rating: 4.7,
      tag: [Tags.SportsCar, Tags.Luxury],
      scale: "1:18"),
  Car(
      name: "Lamborghini Sian FKP 37 ",
      img: [
        "assets/images/lambo/lambo7.png",
        "assets/images/lambo/lambo6.png",
        "assets/images/lambo/lambo5.png",
        "assets/images/lambo/lambo4.png",
        "assets/images/lambo/lambo3.png",
        "assets/images/lambo/lambo2.png",
        "assets/images/lambo/lambo1.png",
      ],
      details: "details",
      highlights: highlights,
      price: 199,
      tag: [
        Tags.SuperCar,
      ],
      rating: 4.2,
      scale: " 1:18"),
  Car(
      name: "Lamborghini Urus grey",
      img: [
        "assets/images/urus/urus6.png",
        "assets/images/urus/urus5.png",
        "assets/images/urus/urus4.png",
        "assets/images/urus/urus3.png",
        "assets/images/urus/urus2.png",
        "assets/images/urus/urus1.png",
      ],
      details: "details",
      highlights: highlights,
      tag: [Tags.SportsCar, Tags.Luxury, Tags.SUV],
      price: 120,
      rating: 3.9,
      scale: "1:20"),
];
